language: ruby
cache: bundler
bundler_args: --deployment

rvm:
  - 2.2.1

env:
  matrix:
    - TEST_SUITE=rspec
    - TEST_SUITE=cucumber
  global:
    - "COVERALLS_ENDPOINT=aschwartz-429.dev.enova.com:3000"
script: bundle exec $TEST_SUITE
